language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

install:

  # Install a custom version of shellcheck instead of Travis CI's default
  - scversion="stable" # or "v0.4.7", or "latest"
  - wget "https://storage.googleapis.com/shellcheck/shellcheck-$scversion.linux.x86_64.tar.xz" | tar -xJf - # wget the file and unzip it using gzip and then untar it
  - shellcheck() { "shellcheck-$scversion/shellcheck" "$@"; }
  - shellcheck --version

script:
  - shellcheck *.sh

matrix:
  fast_finish: true
