language: cpp

matrix:
  include:
    - os: osx
    - os: linux
      dist: xenial
      sudo: required
      before_install:
       - sudo apt-get install -y libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev libcups2-dev libasound2
       - sudo ln -s /usr/lib/x86_64-linux-gnu/libasound.so.2 /usr/lib/x86_64-linux-gnu/libasound.so

before_script:
 - unset -v _JAVA_OPTIONS
 - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
script: 
 - source install-jdk.sh -f 10
 - bash -c './makejdk-any-platform.sh jdk11u'
