language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

install:

script:
  - ./shellcheck.sh
  - cd version-parser && ./test-version-parser.sh

matrix:
  fast_finish: true
