language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

install:

  # Install a custom version of shellcheck instead of Travis CI's default
  - ./shellchek.sh install

script:
  - ./shellcheck.sh check

matrix:
  fast_finish: true
