---

# Usage: ansible-playbook -s --ask-sudo-pass ubuntu_14_x86.yml

- hosts: local

  tasks:

  - name: Install tools
    apt: name={{item}} state=installed
    with_items:
      - make
      - gcc
      - g++
      - openjdk-7-jdk
      - libx11-dev
      - libxext-dev 
      - libxrender-dev
      - libxtst-dev
      - libxt-dev
      - libcups2-dev
      - libasound2-dev
      - ccache
      - zip
