name: Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    strategy:
      matrix:
        os: [linux]
        version: [jdk8u, jdk11u, jdk16, jdk]
        vm: [hotspot, openj9]
        image: [adoptopenjdk/centos7_build_image]
        include:
          - os: alpine-linux
            version: jdk16
            vm: hotspot
            image: adoptopenjdk/alpine3_build_image
          - os: alpine-linux
            version: jdk
            vm: hotspot
            image: adoptopenjdk/alpine3_build_image
          - os: linux
            version: jdk11u
            vm: dragonwell
            image: adoptopenjdk/centos7_build_image
    steps:
    - uses: actions/checkout@v2
        
    - name: Build Linux
      run: ./build-farm/make-adopt-build-farm.sh
      env:
        JAVA_TO_BUILD: ${{ matrix.version }}
        ARCHITECTURE: x64
        VARIANT: ${{ matrix.vm }}
        TARGET_OS: ${{ matrix.os }}
        FILENAME: OpenJDK.tar.gz

  build_windows:
     name: Windows
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
         os: [windows-2016]
         version: [jdk11u, jdk16, jdk]
         vm: [hotspot]
         include:
          - os: windows-2016
            version: jdk11u
            vm: openj9
          - os: windows-2019
            version: jdk16
            vm: openj9
          - os: windows-2019
            version: jdk
            vm: openj9

     steps:
     - name: Restore cygwin packages from cache
       id: cygwin
       uses: actions/cache@v2
       with:
        path: C:\cygwin_packages
        key: cygwin-packages-${{ runner.os }}-v1

     - name: Install Cygwin
       run: |
         New-Item -Path C:\ -Name 'openjdk' -ItemType 'directory'
         Invoke-WebRequest -UseBasicParsing 'https://cygwin.com/setup-x86_64.exe' -OutFile 'C:\temp\cygwin.exe'
         Start-Process -Wait -FilePath 'C:\temp\cygwin.exe' -ArgumentList '--packages autoconf,automake,bsdtar,cpio,curl,gcc-core,git,gnupg,grep,libtool,make,mingw64-x86_64-gcc-core,perl,rsync,unzip,wget,zip --quiet-mode --download --local-install --delete-orphans --site https://mirrors.kernel.org/sourceware/cygwin/ --local-package-dir C:\cygwin_packages --root C:\cygwin64'

     - uses: actions/setup-java@v1
       id: setup-java7
       with:
         java-version: 7
       if: matrix.version == 'jdk8u'

     - uses: actions/setup-java@v1
       id: setup-java11
       with:
         java-version: 11

     - name: Install Git
       run: |
         Invoke-WebRequest 'https://github.com/git-for-windows/git/releases/download/v2.14.3.windows.1/Git-2.14.3-64-bit.exe' -OutFile 'C:\temp\git.exe'
         Start-Process -Wait -FilePath 'C:\temp\git.exe' -ArgumentList '/SILENT /ALLOWDOWNGRADE=1** /COMPONENTS="icons,ext\reg\shellhere,assoc,assoc_sh"'

     - name: Set PATH
       run: echo "C:\cygwin64\bin;C:\Program Files\Git\bin;" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

     - name: Install Visual Studio 2013
       run: |
         choco install visualstudiocommunity2013
       if: matrix.version == 'jdk8u'

     - name: Install Cuda
       run: |
         Invoke-WebRequest -UseBasicParsing 'https://developer.nvidia.com/compute/cuda/9.0/Prod/network_installers/cuda_9.0.176_win10_network-exe' -OutFile 'C:\temp\cuda_9.0.176_win10_network-exe.exe'
         Start-Process -Wait -FilePath 'C:\temp\cuda_9.0.176_win10_network-exe.exe' -ArgumentList '-s compiler_9.0 nvml_dev_9.0'
       if: matrix.vm == 'openj9'

     - name: Install Freemarker
       run: |
         Invoke-WebRequest 'https://repo.maven.apache.org/maven2/freemarker/freemarker/2.3.8/freemarker-2.3.8.jar' -OutFile 'C:\openjdk\freemarker.jar'
       if: matrix.vm == 'openj9'

     - name: Install Clang
       run: |
         choco install llvm --version=7.0.0
         mklink /D "C:\openjdk\LLVM64" "C:\Program Files\LLVM"
       shell: cmd
       if: matrix.vm == 'openj9'

     - name: Install NASM
       run: |
         Invoke-WebRequest 'https://www.nasm.us/pub/nasm/releasebuilds/2.13.03/win64/nasm-2.13.03-win64.zip' -OutFile 'C:\temp\nasm-2.13.03.zip'
         Expand-Archive -LiteralPath 'C:\temp\nasm-2.13.03.zip' -DestinationPath 'C:\openjdk'
       if: matrix.vm == 'openj9'

     - name: Restore OpenSSL VS2013 from cache
       id: openssl-2013
       uses: actions/cache@v2
       with:
        path: C:\openjdk\OpenSSL-1.1.1h-x86_64-VS2013
        key: openssl-1.1.1h-2013-${{ runner.os }}-v1
       if: matrix.vm == 'openj9' && matrix.version == 'jdk8u'

     - name: Restore OpenSSL VS2017 from cache
       id: openssl-2017
       uses: actions/cache@v2
       with:
        path: C:\openjdk\OpenSSL-1.1.1h-x86_64-VS2017
        key: openssl-1.1.1h-2017-${{ runner.os }}-v1
       if: matrix.vm == 'openj9' && matrix.version != 'jdk8u'

     - name: Download OpenSSL
       run: |
         Invoke-WebRequest -UseBasicParsing 'https://www.openssl.org/source/openssl-1.1.1h.tar.gz' -OutFile 'C:\temp\OpenSSL-1.1.1h.tar.gz'
         cd C:\temp
         tar -xf C:/temp/OpenSSL-1.1.1h.tar.gz --force-local -C C:/temp
       if: matrix.vm == 'openj9'

     - name: Install OpenSSL VS2013
       run: |
         set PATH=C:\Strawberry\perl\bin;C:\openjdk\nasm-2.13.03;%PATH%
         call vcvarsall.bat AMD64
         cd C:\temp\OpenSSL-1.1.1h
         perl C:\temp\OpenSSL-1.1.1h\Configure VC-WIN64A --prefix=C:\openjdk\OpenSSL-1.1.1h-x86_64-VS2013
         nmake install && nmake -f makefile clean
       working-directory: 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC'
       shell: cmd
       if: matrix.vm == 'openj9' && matrix.version == 'jdk8u' && steps.openssl-2013.outputs.cache-hit != 'true'

     - name: Install OpenSSL VS2017
       run: |
         set PATH=C:\Strawberry\perl\bin;C:\openjdk\nasm-2.13.03;%PATH%
         call vcvarsall.bat AMD64
         cd C:\temp\OpenSSL-1.1.1h
         perl C:\temp\OpenSSL-1.1.1h\Configure VC-WIN64A --prefix=C:\openjdk\OpenSSL-1.1.1h-x86_64-VS2017
         nmake install && nmake -f makefile clean
       working-directory: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build'
       shell: cmd
       if: matrix.vm == 'openj9' && matrix.version != 'jdk8u' && steps.openssl-2017.outputs.cache-hit != 'true'

     - name: Cygwin git configuration
       shell: bash
       run: mkdir $HOME && git config --system core.autocrlf false

     - uses: actions/checkout@v2

     - name: Set JAVA_HOME
       run: echo "JAVA_HOME=$(cygpath ${{ steps.setup-java11.outputs.path }})" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

     - name: Set JDK7_BOOT_DIR
       run: echo "JDK7_BOOT_DIR=$(cygpath ${{ steps.setup-java7.outputs.path }})" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
       if: matrix.version == 'jdk8u'

     - name: Build Windows
       run: |
         bash build-farm/make-adopt-build-farm.sh
       shell: cmd
       env:
         JAVA_TO_BUILD: ${{ matrix.version }}
         ARCHITECTURE: x64
         VARIANT: ${{ matrix.vm }}
         TARGET_OS: windows
         FILENAME: OpenJDK.tar.gz 
