name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/centos7_build_image
    strategy:
      matrix:
        version: [jdk8u, jdk11u, jdk15u, jdk]
        vm: [hotspot, openj9]

    steps:
    - uses: actions/checkout@v2
        
    - name: Build Linux
      run: ./build-farm/make-adopt-build-farm.sh
      env:
        JAVA_TO_BUILD: ${{ matrix.version }}
        ARCHITECTURE: x64
        VARIANT: ${{ matrix.vm }}
        TARGET_OS: linux
        FILENAME: OpenJDK.tar.gz

  build_macos:
    name: macOS
    runs-on: macos-latest
    strategy:
      matrix:
        version: [jdk8u, jdk11u]
        vm: [hotspot, openj9]

    steps:
    - uses: actions/checkout@v2

    - name Set env
      run: |
        version=$(echo $matrix.version | tr -d "[:alpha:]")
        echo ::set-env name=BOOTJDK_VERSION::$(($version -1))

    - uses: actions/setup-java@v1
      with:
        java-version: ${{ BOOTJDK_VERSION }}
        
    - name: Build macOS
      run: ./build-farm/make-adopt-build-farm.sh
      env:
        JAVA_TO_BUILD: ${{ matrix.version }}
        ARCHITECTURE: x64
        VARIANT: ${{ matrix.vm }}
        TARGET_OS: mac
        FILENAME: OpenJDK.tar.gz

