name: Build

on:
  pull_request:
    branches: [ master ]

env:
  GITHUB_SHA: ${{ github.sha }}

# Cancel existing runs if user makes another push.
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build_linux:
    uses: "adoptium/temurin-build/.github/workflows/build-linux.yml@${{ GITHUB_SHA }}"

  build_macos:
    uses: "adoptium/temurin-build/.github/workflows/build-mac.yml@${{ GITHUB_SHA }}"

  build_windows:
    uses: "adoptium/temurin-build/.github/workflows/build-windows.yml@${{ GITHUB_SHA }}"
    
