# ********************************************************************************
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made
# available under the terms of the Apache Software License 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
# ********************************************************************************

---
name: Code Freeze New freeze Bot

# Controls when the workflow will run
on:
  pull_request_target:
    branches:
      - '*'
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  codefreeze_new:
    runs-on: ubuntu-latest
    steps:
      - name: Code Freeze Run
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: echo "CODE_FREEZE ${{ github.event.issue.number }}"

      - name: Get pull request target branch
        if: github.event_name == 'pull_request_target' || (github.event_name == 'issue_comment' && github.event.issue.pull_request)
        id: get-pr-target-branch
        run: |
          echo "Getting target branch"
          TARGET_BRANCH="$(gh pr view "$PR_NUMBER" --repo "$REPOSITORY" --json baseRefName --jq '.baseRefName')"
          echo "pr_target_branch=$TARGET_BRANCH" >> "$GITHUB_OUTPUT"
          echo "br=$TARGET_BRANCH"
        env:
          REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if target branch is a code freeze branch
        if: github.event_name == 'pull_request_target' || (github.event_name == 'issue_comment' && github.event.issue.pull_request)
        id: check-freeze-branch
        # Following grep "regex" needs to exactly match the required target branches to "freeze"
        run: |
          if echo "$PR_TARGET_BRANCH" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
            FREEZE_BRANCH="true"
          else
            FREEZE_BRANCH="false"
          fi
          echo "code_freeze_branch=$FREEZE_BRANCH" >> "$GITHUB_OUTPUT"
        env:
          PR_TARGET_BRANCH: ${{ steps.get-pr-target-branch.outputs.pr_target_branch }}

      - name: Code Freeze New
        if: (github.event_name == 'pull_request_target' || (github.event_name == 'issue_comment' && github.event.issue.pull_request)) && steps.check-freeze-branch.outputs.code_freeze_branch == "true"
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: echo "IS CODE_FREEZE ${{ github.event.issue.number }}"

